[package]
name = "workflow-llm"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
naaf-model = { path = "../model" }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }
workflow-core = { path = "../workflow-core" }