[package]
name = "naaf-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "naaf"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "help", "std"] }
naaf-builtins.workspace = true
naaf-core.workspace = true
naaf-schema.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true }
uuid.workspace = true
