[package]
name = "dynamic-workflow"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
naaf-core = { path = "../../crates/core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
