[package]
name = "composed-workflow"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
naaf-core = { path = "../../crates/core" }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
