[package]
name = "naaf-orchestrator"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true, features = ["now", "serde"] }
naaf-model.workspace = true
naaf-openspec.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true, features = ["attributes", "std"] }
uuid = { workspace = true, features = ["serde", "v4"] }
