[package]
name = "naaf-llm"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures = { workspace = true, features = ["alloc", "std"] }
glob.workspace = true
naaf-core = { path = "../core" }
reqwest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["io-std", "io-util", "sync"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["openai", "web-search"]
openai = ["dep:reqwest"]
web-search = ["dep:reqwest"]
