[package]
name = "naaf-llm"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
naaf-core.workspace = true
naaf-providers.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
